Repository tango-controls/cppTango, pull requests merged in 2020-11, with the labels that each got.

#778 Backport fix 675 no archive periodic events after polling restart
  cpp_test_suite/new_tests/cxx_dserver_misc.cpp
Labels: Ready For Merge

#800 Revise developer documentation
  CONTRIBUTE.md
  CONTRIBUTING.md
  INSTALL.md
  README.md
  configure/toolchain-i686.cmake
Labels: Ready For Merge, high priority

#779 Include dependencies as SYSTEM libraries
  configure/CMakeLists.txt
  configure/cmake_linux.cmake
  configure/cmake_win.cmake
Labels: EasyToReview, Ready For Merge

#785 CHANGELOG.md: Update
  CHANGELOG.md
Labels: 9.3 backport, Ready For Merge

#746 Event unsubscription from DeviceProxy destructor
  cpp_test_suite/new_tests/cxx_dserver_misc.cpp
  cppapi/client/event.cpp
  cppapi/client/eventconsumer.h
  cppapi/client/eventkeepalive.cpp
  cppapi/client/notifdeventconsumer.cpp
  cppapi/client/zmqeventconsumer.cpp
Labels: EasyToReview, Ready For Merge, high priority

#808 Search docker for tests
  CMakeLists.txt
  cpp_test_suite/environment/run_with_fixture.sh.cmake
  cpp_test_suite/environment/setup_database.sh.cmake
Labels: EasyToReview, Ready For Merge
