Repository tango-controls/cppTango, pull requests merged in 2020-04, with the labels that each got.

#699 Fix issue where unsubscribing in push_events led to API_EventTimeout …
  cppapi/client/zmqeventconsumer.cpp
Labels: 9.3 backport, Ready For Merge, high priority

#692 Always allow to change attribute alarm thresholds
  cpp_test_suite/new_tests/cxx_attr_misc.cpp
  cpp_test_suite/new_tests/cxx_mem_attr.cpp
  cppapi/server/attrgetsetprop.cpp
Labels: Ready For Merge

#694 Send attribute configuration event to all clients after device restart
  cpp_test_suite/new_tests/cxx_dserver_misc.cpp
  cppapi/server/device.cpp
  cppapi/server/dserver.cpp
Labels: Candidate For Backport

#708 Fix tango const comma
  cppapi/server/tango_const.h.in
Labels: Candidate For Backport, Ready For Merge

#709 Remove extra comma
  cppapi/server/tango_const.h.in
Labels: 9.3 backport, Ready For Merge

#659 Remove fallback snprintf implementation
  log4tango/config/check_snprintf.cpp
  log4tango/config/config.cmake
  log4tango/config/config.h.in
  log4tango/include/log4tango/config-win32.h
  log4tango/src/StringUtil.cpp
  log4tango/src/snprintf.c
Labels: Ready For Merge

#700 Upgrade llvm in warning as errors CI tests
  .travis/llvm-latest/Dockerfile
  cppapi/server/attrgetsetprop.cpp
  cppapi/server/eventcmds.cpp
  cppapi/server/fwdattribute.cpp
Labels: Ready For Merge

#673 Switch to python3 for tests
  .travis/debian10/Dockerfile
  .travis/debian8/Dockerfile
  .travis/debian9/Dockerfile
  .travis/gcc-latest/Dockerfile
  .travis/llvm-latest/Dockerfile
  .travis/ubuntu-20.04/Dockerfile
  cpp_test_suite/build_runner.bat
  cpp_test_suite/cxxtest/CMakeLists.txt
  cpp_test_suite/cxxtest/bin/cxxtestgen.py
Labels: Ready For Merge
