Repository tango-controls/cppTango, pull requests merged in 2020-07, with the labels that each got.

#564 Use map for attribute lookup in MultiAttribute::check_associated
  cppapi/server/multiattribute.cpp
Labels: Candidate For Backport, Ready For Merge

#732 Require C++14 standard
  CMakeLists.txt
  configure/CMakeLists.txt
  configure/cmake_pch_linux.cmake
Labels: Ready For Merge

#738 Use map for attribute lookup in MultiAttribute::check_associated
  cppapi/server/multiattribute.cpp
Labels: 9.3 backport, Ready For Merge

#741 log4tango: Use BUILD_TESTING option
  log4tango/CMakeLists.txt
Labels: Candidate For Backport

#743 log4tango: Use BUILD_TESTING option
  log4tango/CMakeLists.txt
Labels: 9.3 backport, Ready For Merge
