Repository tango-controls/cppTango, pull requests merged in 2020-03, with the labels that each got.

#690 Backport: appveyor.yml: Add inline deployment on tag push
  appveyor.yml
Labels: 9.3 backport, high priority

#668 CMakeLists.txt: Add option to disable building the test suite
  CMakeLists.txt
  INSTALL.md
  appveyor.yml
Labels: Ready For Merge

#687 Fix omniidl error checks
  cppapi/server/idl/CMakeLists.txt
Labels: Ready For Merge

#593 Bump release nb
  CMakeLists.txt
Labels: Ready For Merge

#655 Cleanup taco
  cppapi/client/attr_proxy.cpp
  cppapi/client/devapi.h
  cppapi/client/devapi_base.cpp
Labels: Ready For Merge

#573 Fix #496 blind event clients after dev restart (attempt 2)
  cpp_test_suite/new_tests/cxx_dserver_misc.cpp
  cppapi/server/CMakeLists.txt
  cppapi/server/attribute.cpp
  cppapi/server/attribute.h
  cppapi/server/device.cpp
  cppapi/server/device.h
  cppapi/server/dserver.cpp
  cppapi/server/dserver.h
  cppapi/server/event_subscription_state.h
  cppapi/server/eventcmds.cpp
  cppapi/server/multiattribute.cpp
  cppapi/server/multiattribute.h
Labels: Ready For Merge, high priority

#681 9.3 backport to fix #330
  cpp_test_suite/cpp_test_ds/DevTest.cpp
  cpp_test_suite/cpp_test_ds/DevTest.h
  cpp_test_suite/cpp_test_ds/IOMisc.cpp
  cpp_test_suite/cpp_test_ds/TypeCmds.cpp
  cpp_test_suite/new_tests/cxx_attr_misc.cpp
  cppapi/server/attribute.cpp
  cppapi/server/attribute.h
  cppapi/server/device.cpp
  cppapi/server/log4tango.h
Labels: 9.3 backport, Ready For Merge

#642 Allow different paths for CPPZMQ and ZMQ
  appveyor.yml
  configure/cmake_win.cmake
Labels: Candidate For Backport, Ready For Merge

#701 Enforce non-interactive package installation in CI
  .travis/debian10/Dockerfile
  .travis/debian8/Dockerfile
  .travis/debian9/Dockerfile
  .travis/gcc-latest/Dockerfile
  .travis/llvm-latest/Dockerfile
  .travis/ubuntu-20.04/Dockerfile
Labels: Ready For Merge
