Repository tango-controls/cppTango, pull requests merged in 2020-09, with the labels that each got.

#574 Fix 566 const reference parameters
  cppapi/client/DeviceAttribute.h
  cppapi/client/DeviceData.h
  cppapi/client/DevicePipe.h
  cppapi/client/api_util.cpp
  cppapi/client/devapi.h
  cppapi/client/devapi_attr.cpp
  cppapi/client/devapi_data.cpp
  cppapi/client/devapi_datahist.cpp
  cppapi/client/devapi_pipe.cpp
  cppapi/client/devapi_pipe.tpp
  cppapi/client/devapi_utils.cpp
  cppapi/server/attribute.cpp
  cppapi/server/attribute.h
  cppapi/server/templ_inst.cpp
Labels: Ready For Merge

#758 Allow turning shared library building off
  .travis.yml
  .travis/run.sh
  CMakeLists.txt
  INSTALL.md
  appveyor.yml
  configure/CMakeLists.txt
  configure/cmake_linux.cmake
  configure/cmake_pch_linux.cmake
  configure/cmake_pch_win.cmake
  configure/cmake_win.cmake
  configure/cmake_win_defs.cmake
  configure/coveralls.cmake
  configure/cpack_linux.cmake
  configure/cpack_win.cmake
  cppapi/server/CMakeLists.txt
  cppapi/server/jpeg/CMakeLists.txt
  log4tango/config/config.cmake
  log4tango/src/CMakeLists.txt
  log4tango/tests/CMakeLists.txt
Labels: Ready For Merge

#763 Allow turning shared library building off
  .travis.yml
  .travis/run.sh
  .travis/test.sh
  CMakeLists.txt
  INSTALL.md
  configure/CMakeLists.txt
  configure/cmake_linux.cmake
Labels: 9.3 backport, Ready For Merge, high priority

#704 Correct archive periodic event sending after polling restart
  cpp_test_suite/new_tests/cxx_dserver_misc.cpp
  cppapi/server/attribute.cpp
Labels: Candidate For Backport, Ready For Merge, high priority
