Repository tango-controls/cppTango, pull requests merged in 2020-02, with the labels that each got.

#674 Add switch to disable building MMX
  configure/CMakeLists.txt
  cppapi/server/jpeg_mmx/CMakeLists.txt
Labels: 9.3 backport, Candidate For Forwardport, Ready For Merge

#677 Fix memory leak in Attribute::get_att_device_class()
  cppapi/server/attribute.cpp
Labels: 9.3 backport

#678 Fix memory leak in Attribute::get_att_device_class()
  cppapi/server/attribute.cpp
Labels: Ready For Merge

#683 travis.yml: remove deprecated skip_cleanup
  .travis.yml
Labels: 9.3 backport

#676 Add switch to disable mmx build lts
  configure/CMakeLists.txt
  cppapi/server/jpeg_mmx/CMakeLists.txt
Labels: Ready For Merge

#669 appveyor.yml: Fail jobs faster
  appveyor.yml
Labels: Ready For Merge

#689 Backport: CMakeLists.txt: Add option to disable building the test suite
  CMakeLists.txt
  INSTALL.md
  appveyor.yml
Labels: 9.3 backport, Ready For Merge, high priority

#616 appveyor.yml: Add inline deployment on tag push
  appveyor.yml
Labels: Candidate For Backport, Ready For Merge, high priority
