Repository tango-controls/cppTango, pull requests merged in 2020-05, with the labels that each got.

#717 .travis/gcc-latest/Dockerfile: Update to 10.1.0
  .travis/gcc-latest/Dockerfile
  cpp_test_suite/asyn/asyn_write_cb.cpp
Labels: Ready For Merge

#716 Fix nb_endpoints in ZmqEventConsumer::connect_event_channel
  cppapi/client/zmqeventconsumer.cpp
Labels: 9.3 backport, Candidate For Forwardport, Ready For Merge

#688 Shared/static switching on windows
  appveyor.yml
  configure/CMakeLists.txt
  configure/cmake_win.cmake
  configure/cmake_win_defs.cmake
  configure/cpack_win.cmake
  cppapi/client/CMakeLists.txt
  cppapi/server/CMakeLists.txt
  cppapi/server/idl/CMakeLists.txt
  cppapi/server/jpeg/CMakeLists.txt
  cppapi/server/jpeg_mmx/CMakeLists.txt
  log4tango/src/CMakeLists.txt
Labels: Ready For Merge

#702 Backport fix for #496 and #361 - event clients lost after dev restart
  cpp_test_suite/new_tests/cxx_dserver_misc.cpp
  cppapi/server/device.cpp
  cppapi/server/device.h
  cppapi/server/dserver.cpp
  cppapi/server/dserver.h
  cppapi/server/multiattribute.cpp
  cppapi/server/multiattribute.h
Labels: 9.3 backport, Ready For Merge, high priority
