Repository tango-controls/cppTango, pull requests merged in 2020-01, with the labels that each got.

#646 Fix lintian spelling-error-in-binary: occured -> occurred
  cppapi/client/group.cpp
  cppapi/client/group.h
  log4tango/include/log4tango/Appender.hh
  log4tango/log4tango.m4
Labels: Ready For Merge

#647 Fix lintian spelling-error-in-binary: occured -> occurred
  cppapi/client/group.cpp
  cppapi/client/group.h
  log4tango/include/log4tango/Appender.hh
  log4tango/log4tango.m4
Labels: Ready For Merge

#605 Add warning error testing with clang
  .travis.yml
  .travis/llvm-latest/Dockerfile
  cppapi/client/event.cpp
  cppapi/client/eventconsumer.h
  cppapi/client/helpers/DeviceProxyHelper.h
  cppapi/server/attrprop.h
  cppapi/server/dserverpoll.cpp
  cppapi/server/tango_const.h.in
  cppapi/server/templ_inst.cpp
  cppapi/server/utils_polling.cpp
Labels: Ready For Merge

#552 Fix crash when reading a forwarded State attribute #550
  cpp_test_suite/cpp_test_ds/fwd_ds/FwdTestClass.cpp
  cpp_test_suite/cpp_test_ds/fwd_ds/FwdTestClass.h
  cpp_test_suite/new_tests/conf_devtest.cpp
  cpp_test_suite/new_tests/cxx_fwd_att.cpp
  cppapi/client/devapi_attr.cpp
  cppapi/server/attrsetval.cpp
Labels: Ready For Merge

#650 log4tango: Fix snprintf test
  log4tango/m4/AC_FUNC_SNPRINTF.m4
Labels: CandidateForBackport, Log for Tango, Ready For Merge

#658 [Backport] log4tango: Fix snprintf test
  log4tango/m4/AC_FUNC_SNPRINTF.m4
Labels: Ready For Merge

#640 Reset database and device servers for each test (attempt 2)
  .travis.yml
  .travis/debian10/Dockerfile
  .travis/debian7/Dockerfile
  .travis/debian8/Dockerfile
  .travis/debian9/Dockerfile
  .travis/test.sh
  .travis/ubuntu-20.04/Dockerfile
  INSTALL.md
  cpp_test_suite/CMakeLists.txt
  cpp_test_suite/CTestCustom.cmake
  cpp_test_suite/asyn/CMakeLists.txt
  cpp_test_suite/cxxtest/CMakeLists.txt
  cpp_test_suite/cxxtest/bin/kill_server.sh.cmake
  cpp_test_suite/cxxtest/bin/start_server.sh.cmake
  cpp_test_suite/cxxtest/include/config.h.cmake
  cpp_test_suite/environment/CMakeLists.txt
  cpp_test_suite/environment/kill_server.sh.cmake
  cpp_test_suite/environment/post_test.sh.cmake
  cpp_test_suite/environment/pre_test.sh.cmake
  cpp_test_suite/environment/run.sh.cmake
  cpp_test_suite/environment/run_with_fixture.sh.cmake
  cpp_test_suite/environment/setup.sh
  cpp_test_suite/environment/setup_database.sh.cmake
  cpp_test_suite/environment/setup_devices.sh.cmake
  cpp_test_suite/environment/shutdown.sh
  cpp_test_suite/environment/start_server.sh.cmake
  cpp_test_suite/environment/tango_host.cmake
  cpp_test_suite/event/CMakeLists.txt
  cpp_test_suite/old_tests/CMakeLists.txt
Labels: Ready For Merge

#654 Fix interface name collission on MSC_VER = 1900
  cppapi/server/dintrthread.h
Labels: CandidateForBackport, Ready For Merge

#664 [Backport] Avoid undefined interface warning msvc
  cppapi/server/dintrthread.h
Labels: Ready For Merge

#641 Fix race conditions between polling threads and user threads pushing events
  cppapi/server/attribute.cpp
  cppapi/server/attribute.h
  cppapi/server/eventsupplier.cpp
  cppapi/server/eventsupplier.h
Labels: CandidateForBackport, Ready For Merge

#665 [Backport] Fix race conditions between polling threads and user threads pushing events
  cppapi/server/attribute.cpp
  cppapi/server/eventsupplier.cpp
  cppapi/server/eventsupplier.h
Labels: 9.3 backport, Ready For Merge
