Repository tango-controls/cppTango, pull requests merged in 2021-01, with the labels that each got.

#783 cppapi/server/jpeg_mmx/jpeg_dct_mmx.cpp: Remove calling GCC internal functions
  cppapi/server/jpeg_mmx/jpeg_dct_mmx.cpp
Labels: Candidate For Backport, EasyToReview, Ready For Merge, high priority

#818 Fix a bug in FileDatabase::DbGetClassProperty (#816)
  cppapi/client/filedatabase.cpp
Labels: Candidate For Forwardport

#803 cpp_test_suite/event/event_lock.cpp: Make it compile on 32-bit linux
  cpp_test_suite/event/event_lock.cpp
Labels: EasyToReview, Ready For Merge

#828 cppapi/server/jpeg_mmx/jpeg_dct_mmx.cpp: Avoid using the wrong GCC fu…
  cppapi/server/jpeg_mmx/jpeg_dct_mmx.cpp
Labels: 9.3 backport, Ready For Merge

#755 Bugfix/fix abi checking
  .github/workflows/c-cpp.yml
  .travis/check-ABI-API-compliance.sh
Labels: Candidate For Backport, Ready For Merge, high priority
